### ISSUE TITLE
Adding work requirements

### ISSUE THREAD

**Issue by codykallen** [open-source-economics/PFLCM#4]
The current approach only uses FMLA eligibility rules to estimate take-up behavior from the FMLA dataset. However, it does not apply any eligibility rules in the CPS dataset. This approach essentially assumes that leave is job protected (implying that take-up and duration patterns should come from those taking job-protected leave), and but that there are no eligibility requirements other than that one must be employed. 

To implement a work-hours requirement, we would need to estimate total hours worked annually, either "currently" or during the past year. The "current" approach would estimate hours by multiplying `WKSWORK` (weeks worked) by `HRSWK` (hours worked per week). 

I think this is the best approach. However, there are potential other variables that could be used for this, including:
 - `WEWKRS`: weeks worked last year
 - `PEHRUSLT`: hours per week usually worked at all jobs

**Comment by begitis** [comment]
When estimating impact of a work-hours requirement, I use the "current" approach: estimate hours by multiplying WKSWORK by HRSWK.

**Comment by codykallen** [comment]
@begitis provided the clarification:

> When estimating impact of a work-hours requirement, I use the "current" approach: estimate hours by multiplying WKSWORK by HRSWK.

Given this, it should be fairly straightforward to implement the work requirements by modifying the CPS file. There are several places in the code at which this could be done. For the following options, assume that we have already defined the parameter for the hours worked requirement as `hoursworked_requirement`, and that total hours worked is measured as `TOTALHOURS = WKSWORK * HRSWK`. 

1. Add the line
`replace leave_expdur = 0 if TOTALHOURS < hoursworked_requirement`

2. Add the line
`replace weekly_benefit = 0 if TOTALHOURS < hoursworked_requirement`

3. Add the line
`replace leave_total = 0 if TOTALHOURS < hoursworked_requirement`

Note that these lines would need to be implemented in the proper places in the code, preferably immediately after defining the relevant terms to be replaced. If implemented correctly, these 3 lines would all have the same effect. 

I should also note that adding a work-hours requirement does not cause the loss of any observations, as all observations that are not missing `WKSWORK` (currently used) are also not missing `HRSWK`. 

If anyone has a preference on which method to use, please suggest it. Otherwise, I will use the line (1. `replace leave_expdur`). Also, I am open to alternative suggestions for the parameter name, as `hoursworked_requirement` is a bit clunky.

**Comment by codykallen** [comment]
This has been resolved by PR #5.
